# Generated by Django 6.1.1 on 2026-09-09 05:59

import scheduling.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manage_token', models.CharField(default=scheduling.models._new_token, editable=False, max_length=64, unique=True)),
                ('client_name', models.CharField(max_length=120)),
                ('client_email', models.EmailField(max_length=254)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'confirmed')), fields=('start_at',), name='unique_confirmed_start')],
            },
        ),
    ]
