# Generated by Django 6.1.1 on 2026-09-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slot_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
