# Generated by Django 6.1.1 on 2026-09-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_booking_slot_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='calendar_event_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='meet_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
