# Generated by Django 6.1.1 on 2026-09-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_booking_calendar_event_id_booking_meet_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.CharField(blank=True, choices=[('headhunting', 'Headhunting'), ('japan', 'Japan services'), ('global', 'Wanted Global service introduction')], default='', max_length=20),
        ),
    ]
