# Generated by Django 6.1.1 on 2026-09-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_booking_service'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_confirmed_start',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('service', 'japan'), ('status', 'confirmed')), fields=('start_at',), name='unique_confirmed_start_japan'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'confirmed'), models.Q(('service', 'japan'), _negated=True)), fields=('start_at',), name='unique_confirmed_start_main'),
        ),
    ]
